# Generated by Django 5.2.1 on 2025-06-26 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistration_price_at_purchase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_tickets', to='events.eventregistration')),
            ],
        ),
    ]
