# Generated by Django 5.2.1 on 2025-05-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siteconfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_title', models.CharField(max_length=200)),
                ('navbar_image', models.ImageField(upload_to='Siteconfig/')),
                ('headers_name', models.CharField(max_length=100)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict, null=True)),
                ('homepage_banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('is_maintenance', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
            },
        ),
    ]
